version: '3'
services:
  db:
    build: ./db
    # environment:
      # MYSQL_ROOT_PASSWORD: 'fagprove'
    ports:
      - '3306:3306'
  backend:
    build: ./backend
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"