version: '3'
services:
  data:
    container_name: mysql_data
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    command: "true"

  db:
    build: ./db
    ports:
      - '3306:3306'
      - '3307:3306'
    volumes_from:
      - data
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
